### ISSUE TITLE
requirements?

### ISSUE THREAD

**Issue by Echsecutor** [vitovt/ping_graph#1]
Running the tool as described in https://github.com/vitovt/ping_graph?tab=readme-ov-file#usage does not work due to (possibly) missing python packages. -> which packages need to be installed?

**Comment by vitovt** [comment]
Hi.
Full list of imported packages is in import section of code:
```
import subprocess
import re
import time as tme
import matplotlib.pyplot as plt
import argparse
import threading
import numpy as np
```
At least **subprocess**, **time**, **threading**

If you paste here the screenshot of error I can give you more detailed advice.

Regards.

**Comment by vitovt** [comment]
Here is the dependecy commit: https://github.com/vitovt/ping_graph/commit/8a815aaa1408e189934ff3e54c1e14a76741fdeb
