### ISSUE TITLE
package loss not shown

### ISSUE THREAD

**Issue by Echsecutor** [vitovt/ping_graph#3]
In an environment with sporading time windows where the server looses all packages, this graph records 1 ping of max timeout (150 ms default), although the server might have been not responding for seconds. In this case even the default output of `ping` showing the minimal statistics

Example:
```
269 packets transmitted, 149 received, 44.6097% packet loss, time 270921ms
rtt min/avg/max/mdev = 27.158/35.798/493.559/48.388 ms
```

is much more useful than the corresponding graph that has only few 150ms spike and hence looks quite ok. ;) 

Could you add a pacakge loss count? Maybe indicate each package loss in the graph by e.g. a red bar?

**Comment by vitovt** [comment]
I've intended to use this piece of software to investigate latency in my network. But I didn't focus on loss measuring.
Your idea sounds good. But need some code rewriting to fix ping loss measuring (technically lost ping is a ping with delay higher than some threshold, even if it will return back later).

I'll try to deal with it when I will have some free time to make some experiments.
But in any case, your help will be appreciated. Especially dealing with threads in which every ping runs.

**Comment by vitovt** [comment]
Fix HERE https://github.com/vitovt/ping_graph/commit/fd5417ba0ace3d3796d562366d38cf8e21856f1a
 and add more options for timeouts here https://github.com/vitovt/ping_graph/commit/6f3804f254207d80927d9c813d2f49e4870d8d53
